build_task:
  container:
    image: circleci/erlang:21
  rebar3_cache:
    folder: _build
    fingerprint_script: cat rebar.lock
    populate_script: rebar3 compile --deps_only

test_task:
  container:
    image: circleci/erlang:21
  depends_on:
    - build
  rebar3_cache:
    folder: _build
    fingerprint_script: cat rebar.lock
  test_script: rebar3 ct
  always:
    junit_artifacts:
      path: "_build/test/logs/ct_run.*/junit_report.xml"

osx_check_task:
  osx_instance:
    image: mojave-base
  install_script: brew install erlang
  test_script: |
    wget https://s3.amazonaws.com/rebar3/rebar3
    chmod +x rebar3
    ./rebar3 ct
